baseURL = "https://laozhu.me"
languageCode = "zh-Hans"
title = "Ritchie Pub."
theme = "hugo-nuo"
enableRobotsTXT = true
pygmentsuseclasses = true
PygmentsCodeFences = true
canonifyurls = true

# Disqus Username
disqusShortname = "melaozhu"

# Google Analytics UA number
googleAnalytics = "UA-33369276-1"

# Copyright of your post
copyright = "Â© æœ¬ç«™æ‰€æœ‰æ–‡ç« å‡é‡‡ç”¨ã€ŒçŸ¥è¯†å…±äº«ç½²å-éå•†ä¸šæ€§ä½¿ç”¨ 4.0 å›½é™…è®¸å¯åè®®ã€è¿›è¡Œè®¸å¯ï¼Œå¦‚éœ€è½¬è½½è¯·æ³¨æ˜å‡ºå¤„ã€‚"

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "ğŸ  é¦–é¡µ"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "ğŸ’» ä½œå“"
  weight = 20
  identifier = "works"
  url = "https://github.com/laozhu"

# Add your own params here
[params]
  author = "ç±³è€æœ±"
  avatar = "/img/avatar.jpg"
  seotitle = "ç±³è€æœ±çš„åšå®¢ Ritchie Pub."
  subtitle = "~ å¸¦ç€çˆ±å’Œæ¢¦æƒ³ç”Ÿæ´» ~"
  description = "è¿™é‡Œæ˜¯ @ç±³è€æœ± çš„ä¸ªäººåšå®¢ï¼Œè®°å½•ä»–åœ¨äº’è”ç½‘æ–°ä¸–ç•Œæ¢ç´¢çš„ç‚¹ç‚¹æ»´æ»´ã€‚"
  paginate = 10

  # Choose your social accounts
  email = "laozhu.me@gmail.com"
  github = "laozhu"
  twitter = "melaozhu"
  linkedin = "melaozhu"
  weibo = "shiaohoo"
  wechat= "/img/qrcode.jpg"
  # facebook = "melaozhu"
  # google = "109063353665074282689"
  # instagram = "melaozhu"
  # youtube = "melaozhu"
  # vimeo = "melaozhu"
  # medium = "melaozhu"
  # quora = "melaozhu"
  # pinterest = "laozhu"
  # dribbble = "laozhu"
  # behance = "melaozhu"
  # jsfiddle = "laozhu"
  # codepen = "laozhu"
  # zhihu = "melaozhu"
  # douban = "melaozhu"
  # bilibili = "13395348"

  # Changyan Comments (China Only)
  changyan = true
  changyanId = "cyt3toRiB"
  changyanConf = "prod_0908b1cb9a581501753cce1ed074dbe3"

  # Google Webmaster
  # https://www.google.com/webmasters/
  googleSiteVerification = "_moDmnnBNVLBN1rzNxyGUGdPHE20YgbmrtzLIbxaWFc"
  # Bing Webmaster
  # https://www.bing.com/toolbox/webmaster/
  msValidate = "22596E34341DD1D17D6022C44647E587"
  # Baidu Webmaster (China Only)
  # https://zhanzhang.baidu.com/
  baiduSiteVerification = "MZ23SPxxfa"
  # Sogou Webmaster (China Only)
  # http://zhanzhang.sogou.com/
  sogouSiteVerification = "m2jktMQTZm"
  # 360 Webmaster (China Only)
  # http://zhanzhang.so.com/
  soSiteVerification = "b7ab3b4c2edbc856642004d1b8c27a91"
  # Baidu Tongji (China Only)
  # https://tongji.baidu.com/
  baiduTongji = "e21dc1e8a592188271b615159dc88af7"
  # ICP Number (China Only)
  ICP = "è‹ICPå¤‡16005986å·-2"
